@CmsObserver.API_HostAddress = https://localhost:7295

GET {{CmsObserver.API_HostAddress}}/entities

###

GET {{CmsObserver.API_HostAddress}}/entities?includeUnpublished=true

###

@CmsObserver.EntityToDisable = iron-man

POST {{CmsObserver.API_HostAddress}}/admin/entities/{{CmsObserver.EntityToDisable}}/disable

###
