@CmsObserver.API_HostAddress = https://localhost:7295
@CmsObserver.CmsBasicAuth = Basic Y21zaG9va3VzZXIxOjViZTU3ZjUwLTExOTQtNDU5Mi1hMTg1LWRjZjI1YjczYWNlNw==

POST {{CmsObserver.API_HostAddress}}/cms/events
Content-Type: application/json
Accept: application/json
Authorization: {{CmsObserver.CmsBasicAuth}}

[
  {
    "type": "publish",
    "id": "tchalla",
    "timestamp": "2026-01-01T00:20:00Z",
    "payload": {
      "name": "Black Panther",
      "actor": "Chadwick Boseman",
      "movies": ["Black Panther"]
    },
    "version": 1
  },
  {
    "type": "unPublish",
    "id": "tchalla",
    "timestamp": "2026-01-01T00:20:01Z",
    "payload": {
      "name": "Black Panther",
      "actor": "Chadwick Boseman",
      "movies": ["Black Panther", "Black Panther II (Cancelled)"]
    },
    "version": 2
  }
]

###
